library(DBI)
library(dplyr)
library(googlesheets4)


## conexão com banco replica 

con2 <- dbConnect(odbc::odbc(), "reproreplica")


acordos_trat <- dbGetQuery(con2,"
WITH CLI AS (SELECT C.CLICODIGO, CLINOMEFANT,GCLCODIGO GRUPO,SETOR FROM CLIEN C
               LEFT JOIN (SELECT CLICODIGO,ZODESCRICAO SETOR FROM ENDCLI ED
               INNER JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA)Z ON ED.ZOCODIGO=Z.ZOCODIGO
               WHERE ENDFAT='S')E 
               ON C.CLICODIGO=E.CLICODIGO
               WHERE CLICLIENTE='S'),

CLITB AS (SELECT TBPCODIGO,
                   CLINOMEFANT,
                    GRUPO,SETOR,
                     CLITBP.CLICODIGO FROM CLITBP 
                      INNER JOIN CLI ON CLI.CLICODIGO=CLITBP.CLICODIGO),

TOTACORDO AS (SELECT DISTINCT T.TBPCODIGO,TBPPCOVENDA
FROM TBPPRODU T
INNER JOIN CLITB C ON T.TBPCODIGO=C.TBPCODIGO
WHERE PROCODIGO='CONTTB')

SELECT CLICODIGO,
         CLINOMEFANT CLIENTE, 
            GRUPO,T.TBPCODIGO COD_TABELA, 
             SETOR,
              TBPDESCRICAO DESCRICAO,
               TBPDTINICIO INICIO,TBPDTVALIDADE VALIDADE, TBPSITUACAO SITUACAO ,TBPPCOVENDA TOTAL_ACORDO
FROM TABPRECO T
INNER JOIN CLITB ON T.TBPCODIGO=CLITB.TBPCODIGO 
LEFT JOIN TOTACORDO TT ON T.TBPCODIGO=TT.TBPCODIGO
WHERE TBPDESCRICAO LIKE '%TRATAMENTO BONIFICADO%'
AND TBPDTVALIDADE >='YESTERDAY'
ORDER BY  COD_TABELA DESC
") 

View(acordos_trat)

range_write("1FnrTEE_RZyu0qMGB8xYpOlQvg2EFIJdNBbgUG3h4NuY",data=acordos_trat,sheet = "DADOS ACORDOS",
            range = "A1") 

