trat_qtd <- dbGetQuery(con2,"
  EXECUTE BLOCK RETURNS (CLICODIGO INT,
                          NOME VARCHAR(50),
                           GRUPO INT,
                            SETOR VARCHAR(35),
                             ID_PEDIDO VARCHAR(35),
                              EMISSAO DATE,
                               MES INT,
                                DESCRICAO VARCHAR(50),
                                 QTD DECIMAL(15,2), 
                                  VRVENDA DECIMAL(15,2))
AS DECLARE VARIABLE CLI INT;
BEGIN
FOR
WITH TB AS (SELECT TBPCODIGO FROM TABPRECO WHERE TBPDTVALIDADE>='TODAY' 
            AND TBPDESCRICAO LIKE '%TRATAMENTO BONIFICADO%')

SELECT DISTINCT CL.CLICODIGO FROM CLITBP CL
INNER JOIN TB T ON CL.TBPCODIGO=CL.TBPCODIGO

INTO : CLI

DO
BEGIN
FOR
 
  WITH  CLI AS 
  (SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,ZODESCRICAO FROM CLIEN C
   INNER JOIN (SELECT CLICODIGO,E.ZOCODIGO,ZODESCRICAO FROM ENDCLI E
INNER JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA 
WHERE ZOCODIGO IN (20,21,22,23,24,25,28))Z ON E.ZOCODIGO=Z.ZOCODIGO
WHERE ENDFAT='S') ED ON C.CLICODIGO=ED.CLICODIGO
  WHERE C.CLICODIGO IN (SELECT CLICODIGO FROM CLIEN WHERE CLICODIGO=:CLI)),
  
  FIS AS 
  (SELECT FISCODIGO 
    FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
  PED AS 
  (SELECT ID_PEDIDO,P.CLICODIGO,CLINOMEFANT,GCLCODIGO,PEDDTEMIS,ZODESCRICAO
    FROM PEDID P
    INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
    INNER JOIN CLI ON P.CLICODIGO=CLI.CLICODIGO
    WHERE 
    /* CONDITIONAL DATES */ 

PEDDTEMIS >=
( 
CASE
WHEN 
EXTRACT(WEEKDAY FROM CURRENT_DATE)=1 THEN 
DATEADD(-3 DAY TO CURRENT_DATE)
WHEN
EXTRACT(WEEKDAY FROM CURRENT_DATE)=2 THEN 
DATEADD(-3 DAY TO CURRENT_DATE)  ELSE
DATEADD(-1 DAY TO CURRENT_DATE) END
)
AND 
PEDDTEMIS <=( 
CASE
WHEN 
EXTRACT(WEEKDAY FROM CURRENT_DATE)=1 THEN 
DATEADD(-3 DAY TO CURRENT_DATE)
WHEN
EXTRACT(WEEKDAY FROM CURRENT_DATE)=2 THEN 
DATEADD(-1 DAY TO CURRENT_DATE)  ELSE
DATEADD(-1 DAY TO CURRENT_DATE) END
)
--------------------------------------
    
    PEDDTEMIS 
    BETWEEN DATEADD (-EXTRACT(DAY FROM CURRENT_DATE)+1 DAY TO CURRENT_DATE) AND 'TODAY'
    AND PEDSITPED<>'C'),
  
  TAB AS 
  (SELECT C.TBPCODIGO 
    FROM CLITBP C
    INNER JOIN CLI ON C.CLICODIGO=CLI.CLICODIGO
    INNER JOIN (SELECT TBPCODIGO FROM TABPRECO WHERE TBPDTVALIDADE>='TODAY' 
            AND TBPDESCRICAO LIKE '%TRATAMENTO BONIFICADO%')A ON C.TBPCODIGO=A.TBPCODIGO),
  
  PROD AS 
  (SELECT DISTINCT PROCODIGO,TP.TBPCODIGO 
    FROM TBPPRODU TP
    INNER JOIN TAB ON TAB.TBPCODIGO=TP.TBPCODIGO),
  
  PED_PROMO_PAP AS 
  (SELECT P1.ID_PEDIDO ID_PEDIDO_PROMO 
    FROM PDPRD P1
    INNER JOIN PED ON P1.ID_PEDIDO=PED.ID_PEDIDO
    WHERE PROCODIGO='PAP'),
  
  PED_PROMO_PLUGIN AS 
  (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO 
    FROM PEDIDPROMO P2
    INNER JOIN PED ON P2.ID_PEDIDPROMOCAO=PED.ID_PEDIDO),
  
  PED_PROMO_UNION AS 
  (SELECT ID_PEDIDO_PROMO 
    FROM PED_PROMO_PAP UNION
    SELECT ID_PEDIDO_PROMO 
    FROM PED_PROMO_PLUGIN)
  
SELECT CLICODIGO,
        CLINOMEFANT,
         GCLCODIGO,
          ZODESCRICAO,
           PD.ID_PEDIDO,
             PEDDTEMIS,
              EXTRACT(MONTH FROM PEDDTEMIS) MES,
               PDPDESCRICAO,
                PDPQTDADE QTD,
                 PDPUNITLIQUIDO VRVENDA
                  FROM PDPRD PD
                  INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
                  INNER JOIN PROD ON PD.PROCODIGO=PROD.PROCODIGO
                  LEFT OUTER JOIN PED_PROMO_UNION PMU ON PD.ID_PEDIDO=PMU.ID_PEDIDO_PROMO
                  WHERE 
                  ID_PEDIDO_PROMO IS NULL 
                  GROUP BY 1,2,3,4,5,6,7,8,9,10 HAVING PDPUNITLIQUIDO<=1
                  
                  
                INTO :CLICODIGO,
                      :NOME,
                       :GRUPO,
                        :SETOR,
                         :ID_PEDIDO,
                          :EMISSAO,
                           :MES,
                             :DESCRICAO,
                              :QTD,
                               :VRVENDA
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END") 

View(trat_qtd)

range_write("1FnrTEE_RZyu0qMGB8xYpOlQvg2EFIJdNBbgUG3h4NuY",data=extrat,sheet = "EXTRATO",
            range = "A1") 