library(DBI)
library(magrittr)
library(tidyverse)
library(lubridate)

con2 <- dbConnect(odbc::odbc(), "reproreplica", timeout = 10)


#CURRENT MONTH

result_g77 <- dbGetQuery(con2,"
  
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),

PED AS (SELECT ID_PEDIDO,PEDID.CLICODIGO,PEDDTBAIXA FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
   WHERE PEDDTBAIXA BETWEEN '01.06.2022' AND '30.06.2022' AND 
     PEDSITPED<>'C' AND 
      PEDLCFINANC IN ('S','L','N') AND
        CLICODIGO IN (SELECT CLICODIGO FROM CLIEN WHERE GCLCODIGO=77))

SELECT CLICODIGO,PEDDTBAIXA,SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
 FROM PDPRD PD
  INNER JOIN PED P ON P.ID_PEDIDO=PD.ID_PEDIDO
  GROUP BY 1,2

")

result_g77 %>% summarize(v=sum(VRVENDA))

View(result_g77)


